apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-config
  namespace: immich
data:
  postgresql.conf: |
    listen_addresses = '*'
    port = 5432
    
    shared_buffers = 256MB
    effective_cache_size = 1GB
    work_mem = 4MB
    maintenance_work_mem = 64MB
    checkpoint_completion_target = 0.9
    wal_buffers = 16MB
    default_statistics_target = 100
    random_page_cost = 1.1
    effective_io_concurrency = 200
    
    wal_level = replica
    max_wal_senders = 5
    wal_keep_size = 1GB
    hot_standby = on
    hot_standby_feedback = on
    
    archive_mode = on
    archive_command = 'test ! -f /wal-archive/%f && cp %p /wal-archive/%f'
    archive_timeout = 300
    
    synchronous_commit = local
    
    log_min_duration_statement = 250
    log_connections = on
    log_disconnections = on
    log_checkpoints = on
    log_replication_commands = on
    
  pg_hba.conf: |
    local   all             all                                     trust
    host    all             all             127.0.0.1/32            trust
    host    all             all             ::1/128                 trust
    host    replication     immich          0.0.0.0/0               md5
    host    immich          immich          0.0.0.0/0               md5

